services:

  postgres-user:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-user:/var/lib/postgresql

volumes:
  postgres-user:
