services:

  postgres-user:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-user:/var/lib/postgresql

  user-service:
    build: ./user-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user-service?currentSchema=public
    ports:
      - "8081:8080"

volumes:
  postgres-user:
